# Generated by Django 6.0.6 on 2026-06-30 10:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم المعدة')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم التسلسلي')),
                ('location', models.CharField(max_length=100, verbose_name='موقع المعدة في الشركة')),
                ('status', models.CharField(choices=[('active', 'تعمل بكفاءة'), ('maintenance', 'تحت الصيانة'), ('broken', 'متوقفة تماماً')], default='active', max_length=20, verbose_name='حالة المعدة')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MaintenanceTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان المشكلة')),
                ('description', models.TextField(verbose_name='وصف العطل بالتفصيل')),
                ('priority', models.CharField(choices=[('low', 'منخفضة'), ('medium', 'متوسطة'), ('high', 'طارئة جداً')], default='medium', max_length=10, verbose_name='درجة الأهمية')),
                ('is_resolved', models.BooleanField(default=False, verbose_name='هل تم الإصلاح؟')),
                ('reported_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ البلاغ')),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maitenance.equipment', verbose_name='المعدة المتضررة')),
            ],
        ),
    ]
