# Generated by Django 6.0.6 on 2026-06-30 11:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maitenance', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('generator', 'Generator (Bi-weekly Maintenance)'), ('fire_extinguisher', 'Fire Extinguisher'), ('floodlight', 'Floodlight / Emergency Lighting'), ('other', 'Other Equipment')], default='other', max_length=30),
        ),
        migrations.AddField(
            model_name='equipment',
            name='last_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='equipment',
            name='next_maintenance_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='location',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='serial_number',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active / Functional'), ('maintenance', 'Under Maintenance'), ('broken', 'Out of Service')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='equipment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='maitenance.equipment'),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='is_resolved',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High / Urgent')], default='medium', max_length=10),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='reported_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='title',
            field=models.CharField(max_length=200),
        ),
    ]
