# Generated by Django 6.0.6 on 2026-06-30 14:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maitenance', '0002_equipment_category_equipment_last_maintenance_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='created_at',
        ),
        migrations.AddField(
            model_name='equipment',
            name='running_hours',
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('generator', 'Generator (Bi-weekly Maintenance)'), ('fire_extinguisher', 'Fire Extinguisher'), ('floodlight', 'Floodlight / Emergency Lighting'), ('other', 'Other Equipment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='maintenanceticket',
            name='priority',
            field=models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High / Urgent')], max_length=10),
        ),
        migrations.CreateModel(
            name='MaintenanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_taken', models.TextField()),
                ('performed_by', models.CharField(max_length=100)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('equipment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='maitenance.equipment')),
            ],
        ),
    ]
