# Generated by Django 6.0.6 on 2026-07-01 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maitenance', '0003_remove_equipment_created_at_equipment_running_hours_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='last_maintenance_hours',
            field=models.FloatField(default=0.0),
        ),
    ]
