# Generated by Django 6.0.6 on 2026-07-02 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maitenance', '0004_equipment_last_maintenance_hours'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='equipment_pdf',
            field=models.FileField(blank=True, null=True, upload_to='equipment_pdfs/', verbose_name='ملف PDF للمعدة'),
        ),
        migrations.AddField(
            model_name='maintenanceticket',
            name='ticket_pdf',
            field=models.FileField(blank=True, null=True, upload_to='ticket_pdfs/', verbose_name='تقرير الإغلاق PDF'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='category',
            field=models.CharField(choices=[('generator', 'Generator (Bi-weekly Maintenance)'), ('fire_extinguisher', 'Fire Extinguisher'), ('floodlight', 'Floodlight / Emergency Lighting'), ('scaba', 'Scaba'), ('other', 'Other Equipment')], max_length=30),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active / Functional'), ('need maintenance', 'Need Maintenance'), ('Out of Service', 'Out of Service')], default='active', max_length=20),
        ),
    ]
