# Generated by Django 6.0.6 on 2026-07-12 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maitenance', '0005_equipment_equipment_pdf_maintenanceticket_ticket_pdf_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='status',
            field=models.CharField(choices=[('active', 'Active / Functional'), ('Need maintenance', 'Need Maintenance'), ('Out of Service', 'Out of Service')], default='active', max_length=20),
        ),
    ]
