# Generated by Django 6.0.6 on 2026-07-08 02:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BpvSeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='Asset ID / Serial No')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Need inspection', 'Need inspection'), ('Expired', 'Expired'), ('Damaged', 'Damaged')], default='Available', max_length=30, verbose_name='Status')),
                ('last_inspection', models.DateField(blank=True, null=True, verbose_name='Last Inspection Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('seal_type', models.CharField(blank=True, max_length=50, verbose_name='Seal Type/Material')),
            ],
            options={
                'verbose_name': 'BPV Seal',
                'verbose_name_plural': 'BPV Seals',
            },
        ),
        migrations.CreateModel(
            name='Flange',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='Asset ID / Serial No')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Need inspection', 'Need inspection'), ('Expired', 'Expired'), ('Damaged', 'Damaged')], default='Available', max_length=30, verbose_name='Status')),
                ('last_inspection', models.DateField(blank=True, null=True, verbose_name='Last Inspection Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('size', models.CharField(blank=True, max_length=20, verbose_name='Size/Rating')),
            ],
            options={
                'verbose_name': 'Flange',
                'verbose_name_plural': 'Flanges',
            },
        ),
        migrations.CreateModel(
            name='GateValve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='Asset ID / Serial No')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Need inspection', 'Need inspection'), ('Expired', 'Expired'), ('Damaged', 'Damaged')], default='Available', max_length=30, verbose_name='Status')),
                ('last_inspection', models.DateField(blank=True, null=True, verbose_name='Last Inspection Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('valve_size', models.CharField(blank=True, max_length=20, verbose_name='Valve Size')),
            ],
            options={
                'verbose_name': 'Gate valve',
                'verbose_name_plural': 'Gate valves',
            },
        ),
        migrations.CreateModel(
            name='WellheadTree',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('asset_id', models.CharField(max_length=50, unique=True, verbose_name='Asset ID / Serial No')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Need inspection', 'Need inspection'), ('Expired', 'Expired'), ('Damaged', 'Damaged')], default='Available', max_length=30, verbose_name='Status')),
                ('last_inspection', models.DateField(blank=True, null=True, verbose_name='Last Inspection Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('pressure_rating', models.CharField(blank=True, max_length=20, verbose_name='Pressure Rating')),
            ],
            options={
                'verbose_name': 'Wellhead tree',
                'verbose_name_plural': 'Wellhead trees',
            },
        ),
    ]
