# Generated by Django 6.0.6 on 2026-07-08 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpvseal',
            name='asset_id',
        ),
        migrations.AddField(
            model_name='bpvseal',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='bpvseal',
            name='seal_type',
            field=models.CharField(max_length=50, verbose_name='Seal Type/Material'),
        ),
    ]
