# Generated by Django 6.0.6 on 2026-07-08 03:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0002_remove_bpvseal_asset_id_bpvseal_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gatevalve',
            name='valve_size',
        ),
        migrations.AddField(
            model_name='flange',
            name='pressure_rating',
            field=models.CharField(blank=True, max_length=30, verbose_name='Pressure Rating'),
        ),
        migrations.AddField(
            model_name='gatevalve',
            name='pressure_rating',
            field=models.CharField(blank=True, max_length=30, verbose_name='Pressure Rating'),
        ),
        migrations.AddField(
            model_name='gatevalve',
            name='size',
            field=models.CharField(blank=True, max_length=30, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='wellheadtree',
            name='size',
            field=models.CharField(blank=True, max_length=30, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='flange',
            name='size',
            field=models.CharField(blank=True, max_length=30, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='wellheadtree',
            name='pressure_rating',
            field=models.CharField(blank=True, max_length=30, verbose_name='Pressure Rating'),
        ),
    ]
