# Generated by Django 6.0.6 on 2026-07-08 03:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0003_remove_gatevalve_valve_size_flange_pressure_rating_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BpvPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_type', models.CharField(max_length=50, verbose_name='Part Type/Material')),
                ('quantity', models.PositiveIntegerField(default=0, verbose_name='Quantity')),
                ('status', models.CharField(choices=[('Available', 'Available'), ('Need inspection', 'Need inspection'), ('Expired', 'Expired'), ('Damaged', 'Damaged')], default='Available', max_length=30, verbose_name='Status')),
                ('last_inspection', models.DateField(blank=True, null=True, verbose_name='Last Inspection Date')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
            ],
            options={
                'verbose_name': 'BPV Part',
                'verbose_name_plural': 'BPV Parts',
            },
        ),
        migrations.DeleteModel(
            name='BpvSeal',
        ),
    ]
