# Generated by Django 6.0.6 on 2026-07-08 03:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0004_bpvpart_delete_bpvseal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bpvpart',
            name='part_type',
            field=models.CharField(choices=[('Seal 2 IN', 'Seal 2 IN'), ('Seal 5 IN', 'Seal 5 IN'), ('Poppet', 'Poppet'), ('Plunger', 'Plunger'), ('Spring', 'Spring')], default='Seal 2 IN', max_length=50, verbose_name='Part Type/Material'),
        ),
    ]
