# Generated by Django 6.0.6 on 2026-07-08 03:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0005_alter_bpvpart_part_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bpvpart',
            name='last_inspection',
        ),
        migrations.CreateModel(
            name='AssetMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('Out', 'Dispatch / خروج من الساحة'), ('In', 'Return / دخول إلى الساحة')], max_length=10, verbose_name='Movement Type')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity / الكمية')),
                ('destination', models.CharField(max_length=100, verbose_name='Destination / الوجهة (Well or Rig No)')),
                ('received_by', models.CharField(max_length=100, verbose_name='Received By / اسم المستلم أو السائق')),
                ('movement_date', models.DateTimeField(auto_now_add=True, verbose_name='Movement Date & Time')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes / ملاحظات')),
                ('bpv_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.bpvpart', verbose_name='BPV Part')),
                ('flange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.flange', verbose_name='Flange')),
                ('gate_valve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.gatevalve', verbose_name='Gate Valve')),
                ('wellhead_tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.wellheadtree', verbose_name='Wellhead Tree')),
            ],
            options={
                'verbose_name': 'Asset Movement',
                'verbose_name_plural': 'Asset Movements Logs',
            },
        ),
    ]
