# Generated by Django 6.0.6 on 2026-07-09 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0006_remove_bpvpart_last_inspection_assetmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmovement',
            name='destination',
            field=models.CharField(max_length=100, verbose_name='Destination (Well or Rig No)'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='movement_type',
            field=models.CharField(choices=[('Out', 'Dispatch'), ('In', 'Receive')], max_length=10, verbose_name='Movement Type'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='quantity',
            field=models.PositiveIntegerField(default=1, verbose_name='Quantity'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='received_by',
            field=models.CharField(max_length=100, verbose_name='Received By'),
        ),
        migrations.AlterField(
            model_name='bpvpart',
            name='part_type',
            field=models.CharField(choices=[('Seal 2 IN', 'Seal 2 IN'), ('Seal 5 IN', 'Seal 5 IN'), ('Poppet', 'Poppet'), ('Plunger', 'Plunger'), ('Spring', 'Spring')], default='Seal 2 IN', max_length=50, unique=True, verbose_name='Part Type/Material'),
        ),
    ]
