# Generated by Django 6.0.6 on 2026-07-09 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0007_alter_assetmovement_destination_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flange',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Dispatched', 'Dispatched'), ('Need inspection', 'Need inspection'), ('Expired', 'Expired'), ('Damaged', 'Damaged')], default='Available', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='gatevalve',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Dispatched', 'Dispatched'), ('Need inspection', 'Need inspection'), ('Expired', 'Expired'), ('Damaged', 'Damaged')], default='Available', max_length=30, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='wellheadtree',
            name='status',
            field=models.CharField(choices=[('Available', 'Available'), ('Dispatched', 'Dispatched'), ('Need inspection', 'Need inspection'), ('Expired', 'Expired'), ('Damaged', 'Damaged')], default='Available', max_length=30, verbose_name='Status'),
        ),
    ]
