# Generated by Django 6.0.6 on 2026-07-10 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0008_alter_flange_status_alter_gatevalve_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmovement',
            name='delivery_note_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_notes/', verbose_name='Scanned Delivery Note (PDF/Image)'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='delivery_note_no',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Delivery Note No'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='receiver',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Receiver (Received By)'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='sender',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sender (Dispatched By)'),
        ),
    ]
