# Generated by Django 6.0.6 on 2026-07-10 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0009_assetmovement_delivery_note_file_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmovement',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='assetmovement',
            name='sender',
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='Driver_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver_Name (Received By)'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='Sender_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sender_Name (Dispatched By)'),
        ),
    ]
