# Generated by Django 6.0.6 on 2026-07-10 12:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0010_remove_assetmovement_receiver_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmovement',
            name='delivery_note_no',
        ),
    ]
