# Generated by Django 6.0.6 on 2026-07-10 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0011_remove_assetmovement_delivery_note_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmovement',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Delivery Note'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='departure_site',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='From'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='destination_site',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Destination'),
        ),
        migrations.AddField(
            model_name='assetmovement',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='movement_type',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Movement Type'),
        ),
    ]
