# Generated by Django 6.0.6 on 2026-07-10 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0012_assetmovement_delivery_note_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='assetmovement',
            name='destination',
        ),
        migrations.RemoveField(
            model_name='assetmovement',
            name='received_by',
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='Driver_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Driver Name / Transported By'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='Sender_Name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Sender Name (Dispatched By)'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='movement_type',
            field=models.CharField(blank=True, choices=[('Transfer', 'Transfer'), ('Return back', 'Return back'), ('For use', 'For use'), ('Loan', 'Loan'), ('Out', 'Dispatch'), ('In', 'Receive')], max_length=50, null=True, verbose_name='Movement Type'),
        ),
    ]
