# Generated by Django 6.0.6 on 2026-07-11 05:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0013_remove_assetmovement_destination_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovementItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(blank=True, max_length=100, null=True, verbose_name='Serial Number')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Quantity')),
                ('bpv_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.bpvpart', verbose_name='BPV Part')),
                ('flange', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.flange', verbose_name='Flange')),
                ('gate_valve', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.gatevalve', verbose_name='Gate Valve')),
                ('movement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='yard_assets.assetmovement', verbose_name='Movement Reference')),
                ('wellhead_tree', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.wellheadtree', verbose_name='Wellhead Tree')),
            ],
        ),
    ]
