# Generated by Django 6.0.6 on 2026-07-11 05:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0014_movementitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assetmovement',
            name='bpv_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.bpvpart'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='delivery_note',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='delivery_note_file',
            field=models.FileField(blank=True, null=True, upload_to='delivery_notes/'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='flange',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.flange'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='gate_valve',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.gatevalve'),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='serial_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='assetmovement',
            name='wellhead_tree',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='yard_assets.wellheadtree'),
        ),
    ]
