# Generated by Django 6.0.6 on 2026-07-11 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0015_alter_assetmovement_bpv_part_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='flange',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Name (الاسم)'),
        ),
        migrations.AddField(
            model_name='gatevalve',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Name (الاسم)'),
        ),
        migrations.AddField(
            model_name='wellheadtree',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Name (الاسم)'),
        ),
        migrations.AlterField(
            model_name='flange',
            name='asset_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial Number (السيريال)'),
        ),
        migrations.AlterField(
            model_name='gatevalve',
            name='asset_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial Number (السيريال)'),
        ),
        migrations.AlterField(
            model_name='wellheadtree',
            name='asset_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial Number (السيريال)'),
        ),
    ]
