# Generated by Django 6.0.6 on 2026-07-12 00:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0016_flange_name_gatevalve_name_wellheadtree_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='assetmovement',
            name='receiver_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Receiver Name(Received by'),
        ),
        migrations.AlterField(
            model_name='flange',
            name='asset_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='flange',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Name'),
        ),
        migrations.AlterField(
            model_name='gatevalve',
            name='asset_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='gatevalve',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Name'),
        ),
        migrations.AlterField(
            model_name='wellheadtree',
            name='asset_id',
            field=models.CharField(max_length=50, unique=True, verbose_name='Serial Number'),
        ),
        migrations.AlterField(
            model_name='wellheadtree',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Asset Name'),
        ),
    ]
