# Generated by Django 6.0.6 on 2026-07-12 00:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yard_assets', '0017_assetmovement_receiver_name_alter_flange_asset_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='assetmovement',
            old_name='receiver_name',
            new_name='Receiver_Name',
        ),
    ]
